[package]
name = "ue-workshop-scanner"
version = "0.1.0-alpha.3"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/ifBars/UEWorkshopScanner"
readme = "README.md"
description = "Static malware scanner for Unreal Engine Workshop content"
keywords = ["unreal-engine", "steam-workshop", "malware", "security"]
categories = ["command-line-utilities"]
publish = false

[dependencies]
anyhow = "1.0.100"
hex = "0.4.3"
oodle_loader = { path = "vendor/oodle_loader_safe" }
retoc = { git = "https://github.com/trumank/retoc.git", rev = "d034ade1ae8117d4786eaf6b0418d4cf48474d7f" }
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.11.0"

[patch."https://github.com/trumank/repak.git"]
oodle_loader = { path = "vendor/oodle_loader_safe" }

[workspace]
members = [".", "gui"]
default-members = ["."]
resolver = "2"
